
name: input
on: 
  # push:
  #   branches:
  #     - main
  #     - "**"
  workflow_dispatch:  
    inputs:
      name:
        type: choice
        required: true
        options:
          - a
          - b
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        run: echo "${{ inputs.name }}"
  set-env: 
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: echo "MY_ENV=eu-central-1" >> $GITHUB_ENV
  print-env: 
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - name: print env
        run: echo "${{env.MY_ENV}}"   
      - name: envss
        run: env
        
