
name: input feature 2
on: 
  workflow_dispatch:  
    inputs:
      name:
        type: choice
        required: true
        options:
          - a
          - b
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        run: echo "${{ inputs.name }}"
  execute:
    runs-on: ubuntu-latest
    needs: print
    steps:
      - name: check needs
        runs: echo "hi from execute"
