
name: input feature 2
on: 
  workflow_dispatch:  
    inputs:
      name:
        type: choice
        required: true
        options:
          - a
          - b
      print_needed:
        type: boolean
        required: false
        default: false
jobs:
  print:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_needed == true }} 
    steps:
      - name: Check out the code
        run: echo "${{ inputs.name }}"
  execute:
    runs-on: ubuntu-latest
    needs: print
    steps:
      - name: check needs
        run: echo "hi from execute"
