name: Reusable Workflow For NodeJs
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        description: NOde version to be used.
        required: true
        type: string
        default: 16.x
      RUN_TEST:
        description: Pass true to run test.
        required: false
        type: boolean
        default: false  
      VAR_USE:
        required: true
        type: string
      CMD:
        required: true
        type: string
        
jobs:
  Install_nodeJS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build 
        run: npm run build --if-present
      - name: Test
        if: ${{ inputs.RUN_TEST }}
        run: npm run test --if-present
      - name: echo env
        env:
         VAR: ${{ inputs.VAR_USE }}
        run: ${{ inputs.CMD }} 
