name: Workflow for node App
on: 
  push:
    branches: [ main]
jobs:
  liniting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
  node-app-build:      
    strategy:
      matrix:
        versions: [16, 17 ,18]
    needs: liniting
    uses: nmn1/nodejs-git-actions/.github/workflows/nodejs_reuseable.yaml@main
    with:
        NODE_VERSION: ${{ matrix.versions }}
        RUN_TEST: true    
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   - name: Calling Reusable workflow
    
        